### PR TITLE
add ayaneo flip ds

### PR DESCRIPTION
**Pull request by honjow**

### CODE REVIEW

**Comment by antheas** [comment]
whats the plan for the second screen? Thanks

**Comment by honjow** [comment]
> What's the plan for the second screen? Thanks

What does it mean, screen orientation? Left
And I can't find the touch device for the secondary screen

**Comment by antheas** [comment]
No I mean doing something with it. It's a shame to have it there doing nothing

**Comment by honjow** [comment]
> No I mean doing something with it. It's a shame to have it there doing nothing

My initial idea is to simulate it as a touchpad. An advanced idea is to run a program with a UI that simulates a touchpad and a virtual keyboard.
However, as mentioned earlier, its touch input device cannot be found. Perhaps the driver is not installed correctly. And there are currently issues with the touch on the main screen.

**Comment by antheas** [comment]
The screen needs to be on for touch to work. I'm pretty sure about that. There are some displays that support turning on the digitizer without the screen being on but it's rare

Try with `hhd.contrib evdev` on desktop

**Comment by honjow** [comment]
I have tested it in desktop mode before to confirm that both screens are open

This is the latest test
```
Available Devices with the Current Permissions
device /dev/input/event0, name "Lid Switch", phys "PNP0C0D/button/input0", uniq ""
device /dev/input/event1, name "Power Button", phys "PNP0C0C/button/input0", uniq ""
device /dev/input/event2, name "Power Button", phys "LNXPWRBN/button/input0", uniq ""
device /dev/input/event3, name "Video Bus", phys "LNXVIDEO/video/input0", uniq ""
device /dev/input/event4, name "AT Translated Set 2 keyboard", phys "isa0060/serio0/input0", uniq ""
device /dev/input/event5, name "SINO WEALTH 唰匀䈀 䴀漀甀猀攀", phys "usb-0000:c4:00.3-1/input0", uniq ""
device /dev/input/event6, name "SiGma Micro USB KeyBoard", phys "usb-0000:c4:00.3-3/input0", uniq ""
device /dev/input/event7, name "SiGma Micro USB KeyBoard", phys "usb-0000:c4:00.3-3/input1", uniq ""
device /dev/input/event8, name "PC Speaker", phys "isa0061/input0", uniq ""
device /dev/input/event9, name "Goodix Capacitive TouchScreen", phys "input/ts", uniq ""
device /dev/input/event10, name "HD-Audio Generic HDMI/DP,pcm=3", phys "ALSA", uniq ""
device /dev/input/event11, name "HD-Audio Generic HDMI/DP,pcm=7", phys "ALSA", uniq ""
device /dev/input/event12, name "HD-Audio Generic Mic", phys "ALSA", uniq ""
device /dev/input/event13, name "HD-Audio Generic Headphone", phys "ALSA", uniq ""
device /dev/input/event14, name "Microsoft X-Box 360 pad", phys "usb-0000:c4:00.3-4/input0", uniq ""
device /dev/input/event20, name "extest fake device", phys "", uniq ""
device /dev/input/event15, name "Microsoft X-Box 360 pad 0", phys "", uniq ""
```

SINO WEALTH is mouse

**Pull request merged**
